//! Run Zircon userspace programs (userstart) and manage trap/interrupt/syscall.
//!
//! This module implements the kernel side of the Zircon boot protocol.
//! `userstart` is zCore's Rust replacement for Fuchsia's `userboot` -- the
//! first userspace process launched by the kernel.
//!
//! The boot sequence:
//! 1. Parse the ZBI (Zircon Boot Image) to find a bootfs filesystem
//! 2. Find the first program in the bootfs
//! 3. Map it into a new process as executable code
//! 4. Start the process with bootstrap handles
//!
//! If no ZBI is provided or it contains no bootfs, a built-in hello
//! program is used instead (writes a debug message and exits).

use alloc::{boxed::Box, sync::Arc, vec::Vec};
use cfg_if::cfg_if;
use core::{future::Future, pin::Pin};

use xmas_elf::ElfFile;

use hal::{MMUFlags, PAGE_SIZE};
use hal::{TrapReason, UserContextField};
use hal_impl::context::UserContext;
use zircon_object::dev::{Resource, ResourceFlags, ResourceKind};
use zircon_object::ipc::{Channel, MessagePacket};
use zircon_object::kcounter;
use zircon_object::object::{Handle, KernelObject, Rights};
use zircon_object::task::{CurrentThread, ExceptionType, Job, Process, Thread, ThreadState};

use zircon_object::util::elf_loader::ElfExt;
use zircon_object::vm::VmObject;
use zircon_object::ZxError;

/// Embedded vDSO ELF binary (generated by build.rs from zx-syscall-numbers.h).
static VDSO_ELF: &[u8] = include_bytes!(env!("VDSO_BIN"));

use zircon_abi::processargs::*;

// Note: ZBI parsing (userstart_code, extract_program_from_zbi,
// extract_first_file_from_bootfs) was removed. ZBI parsing is now
// done by the userstart userspace program.

fn kcounter_vmos() -> (Arc<VmObject>, Arc<VmObject>) {
    // Provide dummy kcounter VMOs. Real kcounter data requires linker-
    // provided symbols that are only available on x86_64. For petal/userstart
    // testing, dummy VMOs are sufficient.
    use zircon_object::util::kcounter::DescriptorVmoHeader;
    const HEADER_SIZE: usize = core::mem::size_of::<DescriptorVmoHeader>();
    let desc_vmo = VmObject::new_paged(1);
    let arena_vmo = VmObject::new_paged(1);

    let header = DescriptorVmoHeader::default();
    let header_buf: [u8; HEADER_SIZE] = unsafe { core::mem::transmute(header) };
    desc_vmo.write(0, &header_buf).unwrap();
    desc_vmo.set_name("counters/desc");
    arena_vmo.set_name("counters/arena");
    (desc_vmo, arena_vmo)
}

/// Run Zircon `userstart` process and load the ZBI file as the bootfs.
///
/// `userstart` is zCore's Rust replacement for Fuchsia's `userboot`. Instead
/// of loading prebuilt Fuchsia binaries, it generates a minimal userspace
/// program directly in memory that:
/// 1. Writes a debug message via `zx_debug_write`
/// 2. Exits via `zx_process_exit(0)`
///
/// This function is also available as `run_userboot()` for backward compatibility.
pub fn run_userstart(zbi: impl AsRef<[u8]>, cmdline: &str) -> Arc<Process> {
    let job = Job::root();
    let proc = Process::create(&job, "userstart").unwrap();
    let thread = Thread::create(&proc, "userstart").unwrap();
    let resource = Resource::create(
        "root",
        ResourceKind::ROOT,
        0,
        0x1_0000_0000,
        ResourceFlags::empty(),
    );
    let vmar = proc.vmar();

    // Load the userstart ELF binary (embedded at compile time).
    // If USERSTART_ELF was not set, build.rs provides an empty stub.
    let userstart_elf_bytes: &[u8] = include_bytes!(env!("USERSTART_ELF"));
    assert!(
        !userstart_elf_bytes.is_empty(),
        "USERSTART_ELF not set at compile time. Use rootfs-based boot instead."
    );
    let elf = ElfFile::new(userstart_elf_bytes).expect("failed to parse userstart ELF");
    let size = elf.load_segment_size();
    // Map the userstart ELF as a single RWX region.
    // (The binary is small enough that all segments fit in one page.)
    let code_pages = size;
    let code_vmo = VmObject::new_paged(code_pages);
    // Write the raw ELF content -- load_from_elf would fail for small binaries
    // where multiple PT_LOAD segments share a page. Instead, copy segment data
    // directly to the correct offsets.
    for ph in elf.program_iter() {
        if ph.get_type().unwrap() != xmas_elf::program::Type::Load {
            continue;
        }
        let offset = ph.virtual_addr() as usize;
        let file_offset = ph.offset() as usize;
        let file_size = ph.file_size() as usize;
        if file_size > 0 {
            code_vmo
                .write(
                    offset,
                    &userstart_elf_bytes[file_offset..file_offset + file_size],
                )
                .unwrap();
        }
    }
    let code_flags = MMUFlags::READ | MMUFlags::WRITE | MMUFlags::EXECUTE | MMUFlags::USER;
    let entry = vmar
        .map(None, code_vmo, 0, code_pages * PAGE_SIZE, code_flags)
        .unwrap()
        + elf.header.pt2.entry_point() as usize;
    info!(
        "userstart: loaded ELF ({} bytes, entry={:#x})",
        userstart_elf_bytes.len(),
        entry
    );

    // Flush I-cache after loading executable code.
    // On real hardware (Pi 400), the I-cache and D-cache are not coherent.
    // Without this, the CPU may execute stale/zero data from I-cache.
    #[cfg(target_arch = "aarch64")]
    unsafe {
        core::arch::asm!(
            "dsb ish",  // ensure D-cache writes are visible
            "ic iallu", // invalidate entire I-cache
            "dsb ish",  // ensure I-cache invalidation completes
            "isb",      // synchronize instruction stream
        );
        info!("I-cache invalidated after loading userstart");
    }

    // Create the vDSO VMO with syscall trampolines and constants.
    let vdso_vmo = create_vdso_vmo();

    // zbi
    let zbi_vmo = {
        let vmo = VmObject::new_paged(zbi.as_ref().len() / PAGE_SIZE + 1);
        vmo.write(0, zbi.as_ref()).unwrap();
        vmo.set_name("zbi");
        vmo
    };

    // stack
    const STACK_PAGES: usize = 8;
    let stack_vmo = VmObject::new_paged(STACK_PAGES);
    let flags = MMUFlags::READ | MMUFlags::WRITE | MMUFlags::USER;
    let stack_bottom = vmar
        .map(None, stack_vmo.clone(), 0, stack_vmo.len(), flags)
        .unwrap();
    let sp = if cfg!(target_arch = "x86_64") {
        // WARN: align stack to 16B, then emulate a 'call' (push rip)
        stack_bottom + stack_vmo.len() - 8
    } else {
        stack_bottom + stack_vmo.len()
    };

    // Map the vDSO into the process address space as a single
    // contiguous RX block so ld.so.1 can parse ELF headers at base.
    let vdso_total_size = vdso_vmo.len();
    let vdso_flags = MMUFlags::READ | MMUFlags::EXECUTE | MMUFlags::USER;
    let _vdso_code_addr = vmar
        .map(None, vdso_vmo.clone(), 0, vdso_total_size, vdso_flags)
        .unwrap();

    // channel
    let (user_channel, kernel_channel) = Channel::create();
    let handle = Handle::new(user_channel, Rights::DEFAULT_CHANNEL);

    // vDSO child clones for test vDSOs
    let vdso_test1 = vdso_vmo.create_child(false, 0, vdso_vmo.len()).unwrap();
    vdso_test1.set_name("vdso/test1");
    let vdso_test2 = vdso_vmo.create_child(false, 0, vdso_vmo.len()).unwrap();
    vdso_test2.set_name("vdso/test2");

    let crash_log_vmo = VmObject::new_paged(1);
    crash_log_vmo.set_name("crashlog");

    let (desc_vmo, arena_vmo) = kcounter_vmos();

    let instrumentation_data_vmo = VmObject::new_paged(0);
    instrumentation_data_vmo.set_name("UNIMPLEMENTED_VMO");

    // Build handles and handle_info in matching order.
    // Each handle has a PA_* type tag so the receiver can identify
    // handles by type instead of by positional index.
    let handles = alloc::vec![
        Handle::new(proc.clone(), Rights::DEFAULT_PROCESS), // PA_PROC_SELF
        Handle::new(proc.vmar(), Rights::DEFAULT_VMAR | Rights::IO), // PA_VMAR_ROOT
        Handle::new(job, Rights::DEFAULT_JOB),              // PA_JOB_DEFAULT
        Handle::new(resource, Rights::DEFAULT_RESOURCE),    // PA_RESOURCE
        Handle::new(zbi_vmo, Rights::DEFAULT_VMO),          // PA_VMO_BOOTDATA,0
        Handle::new(vdso_vmo, Rights::DEFAULT_VMO | Rights::EXECUTE), // PA_VMO_VDSO,0
        Handle::new(vdso_test1, Rights::DEFAULT_VMO | Rights::EXECUTE), // PA_VMO_VDSO,1
        Handle::new(vdso_test2, Rights::DEFAULT_VMO | Rights::EXECUTE), // PA_VMO_VDSO,2
        Handle::new(crash_log_vmo, Rights::DEFAULT_VMO),    // PA_VMO_BOOTDATA,1
        Handle::new(desc_vmo, Rights::DEFAULT_VMO),         // PA_VMO_BOOTDATA,2
        Handle::new(arena_vmo, Rights::DEFAULT_VMO),        // PA_VMO_BOOTDATA,3
        Handle::new(instrumentation_data_vmo.clone(), Rights::DEFAULT_VMO), // PA_VMO_BOOTDATA,4
        Handle::new(instrumentation_data_vmo.clone(), Rights::DEFAULT_VMO), // PA_VMO_BOOTDATA,5
        Handle::new(instrumentation_data_vmo.clone(), Rights::DEFAULT_VMO), // PA_VMO_BOOTDATA,6
        Handle::new(instrumentation_data_vmo, Rights::DEFAULT_VMO), // PA_VMO_BOOTDATA,7
    ];
    let handle_info = [
        pa_hnd(PA_PROC_SELF, 0),
        pa_hnd(PA_VMAR_ROOT, 0),
        pa_hnd(PA_JOB_DEFAULT, 0),
        pa_hnd(PA_RESOURCE, 0),
        pa_hnd(PA_VMO_BOOTDATA, 0), // ZBI VMO
        pa_hnd(PA_VMO_VDSO, 0),
        pa_hnd(PA_VMO_VDSO, 1),     // test1
        pa_hnd(PA_VMO_VDSO, 2),     // test2
        pa_hnd(PA_VMO_BOOTDATA, 1), // crash log
        pa_hnd(PA_VMO_BOOTDATA, 2), // kcounter names
        pa_hnd(PA_VMO_BOOTDATA, 3), // kcounter arena
        pa_hnd(PA_VMO_BOOTDATA, 4), // instrumentation
        pa_hnd(PA_VMO_BOOTDATA, 5),
        pa_hnd(PA_VMO_BOOTDATA, 6),
        pa_hnd(PA_VMO_BOOTDATA, 7),
    ];

    // Build processargs-formatted message data.
    let argv = Vec::from(cmdline.replace(':', "\0") + "\0");
    let data = zircon_abi::processargs::build_message(&handle_info, &argv);
    let msg = MessagePacket { data, handles };
    kernel_channel.write(msg).unwrap();

    // Pass the vDSO code base address as arg2 to _start(handle, vdso_base).
    // This matches Fuchsia's convention.
    proc.start(&thread, entry, sp, Some(handle), _vdso_code_addr, thread_fn)
        .expect("failed to start main thread");
    proc
}

/// Backward-compatible alias for [`run_userstart`].
pub fn run_userboot(zbi: impl AsRef<[u8]>, cmdline: &str) -> Arc<Process> {
    run_userstart(zbi, cmdline)
}

kcounter!(EXCEPTIONS_USER, "exceptions.user");
kcounter!(EXCEPTIONS_IRQ, "exceptions.irq");
kcounter!(EXCEPTIONS_PGFAULT, "exceptions.pgfault");

fn thread_fn(thread: CurrentThread) -> Pin<Box<dyn Future<Output = ()> + Send + 'static>> {
    Box::pin(run_user(thread))
}

async fn run_user(thread: CurrentThread) {
    hal_impl::thread::set_current_thread(Some(thread.inner()));
    if thread.is_first_thread() {
        thread
            .handle_exception(ExceptionType::ProcessStarting)
            .await;
    };
    thread.handle_exception(ExceptionType::ThreadStarting).await;

    loop {
        // wait
        let mut ctx = thread.wait_for_run().await;
        if thread.state() == ThreadState::Dying {
            break;
        }

        // run
        let tmp_time = hal_impl::timer::timer_now().as_nanos();
        thread.mark_uspace_enter(tmp_time);

        // * Attention
        // The code will enter a magic zone from here.
        // `enter_uspace` will be executed into a wrapped library where context switching takes place.
        // The details are available in the `trapframe` crate on crates.io.
        ctx.enter_uspace();

        // Back from the userspace
        let time = hal_impl::timer::timer_now()
            .as_nanos()
            .saturating_sub(tmp_time);
        thread.time_add(time);
        trace!("back from user: {:#x?}", ctx);
        EXCEPTIONS_USER.add(1);

        // handle trap/interrupt/syscall
        if let Err(e) = handler_user_trap(&thread, ctx).await {
            if let ExceptionType::ThreadExiting = e {
                break;
            }
            thread.handle_exception(e).await;
        }
    }
    thread.handle_exception(ExceptionType::ThreadExiting).await;

    // In Zircon mode, when the root process (userstart) exits, shut down.
    // Only shut down for the "userstart" process, not child processes like "init".
    if thread.is_first_thread() && thread.proc().name() == "userstart" {
        info!("Zircon root process (userstart) exited, shutting down");
        info!("(if QEMU does not exit, press Ctrl-A then X to quit)");
        if !hal_impl::platform::is_hosted() {
            hal_impl::cpu::reset();
        }
    }
}

async fn handler_user_trap(
    thread: &CurrentThread,
    mut ctx: Box<UserContext>,
) -> Result<(), ExceptionType> {
    let reason = ctx.trap_reason();

    if let TrapReason::Syscall = reason {
        let num = syscall_num(&ctx);
        let args = syscall_args(&ctx);
        ctx.advance_pc(reason);
        thread.put_context(ctx);
        let mut syscall = zircon_syscall::Syscall { thread, thread_fn };
        let ret = syscall.syscall(num as u32, args).await as usize;
        thread
            .with_context(|ctx| ctx.set_field(UserContextField::ReturnValue, ret))
            .map_err(|_| ExceptionType::ThreadExiting)?;
        return Ok(());
    }

    thread.put_context(ctx);
    match reason {
        TrapReason::Interrupt(vector) => {
            EXCEPTIONS_IRQ.add(1); // FIXME
            hal_impl::interrupt::handle_irq(vector);
            hal_impl::thread::yield_now().await;
            Ok(())
        }
        TrapReason::PageFault(vaddr, flags) => {
            EXCEPTIONS_PGFAULT.add(1);
            trace!("page fault from user mode @ {:#x}({:?})", vaddr, flags);
            let vmar = thread.proc().vmar();
            match vmar.handle_page_fault(vaddr, flags) {
                Ok(()) => Ok(()),
                Err(ZxError::SHOULD_WAIT) => {
                    // Pager-backed VMO: the pager has been notified.
                    // Yield repeatedly to let the pager supply pages.
                    // The thread will re-fault after this returns Ok(()).
                    trace!("page fault: waiting for pager to supply pages");
                    // Yield multiple times to give the pager process
                    // time to run and supply the requested pages.
                    for _ in 0..100 {
                        hal_impl::thread::yield_now().await;
                    }
                    Ok(())
                }
                Err(err) => {
                    #[cfg_attr(not(target_arch = "x86_64"), allow(unused_variables))]
                    let ctx = thread.context_cloned();
                    error!(
                        "failed to handle page fault from user mode @ {:#x}({:?}): {:?}",
                        vaddr, flags, err,
                    );
                    if let Ok(mf) = thread.proc().vmar().get_mapping_flags(vaddr) {
                        error!("  mapping at fault addr: {:?}", mf);
                    } else {
                        error!("  NO mapping at fault addr {:#x}", vaddr);
                    }
                    // Dump TLS info for debugging unsafe stack pointer issues
                    #[cfg(target_arch = "x86_64")]
                    {
                        let regs2 = ctx.as_ref().unwrap().general();
                        if regs2.fsbase != 0 {
                            let mut tls_buf = [0u8; 32];
                            if thread
                                .proc()
                                .vmar()
                                .read_memory(regs2.fsbase, &mut tls_buf)
                                .is_ok()
                            {
                                error!(
                                    "  fsbase={:#x} TLS[0x10]={:#x} TLS[0x18]={:#x}",
                                    regs2.fsbase,
                                    usize::from_le_bytes(tls_buf[0x10..0x18].try_into().unwrap()),
                                    usize::from_le_bytes(tls_buf[0x18..0x20].try_into().unwrap()),
                                );
                            }
                        }
                    }
                    // Dump user registers and stack backtrace
                    #[cfg(target_arch = "x86_64")]
                    {
                        let regs = ctx.as_ref().unwrap().general();
                        error!(
                            "  rip={:#x} rsp={:#x} rbp={:#x} rdi={:#x} rsi={:#x}",
                            regs.rip, regs.rsp, regs.rbp, regs.rdi, regs.rsi
                        );
                        let mut fp = regs.rbp;
                        for depth in 0..8 {
                            if fp == 0 || fp > 0x8000_0000_0000 {
                                break;
                            }
                            let mut buf = [0u8; 16];
                            if thread.proc().vmar().read_memory(fp, &mut buf).is_ok() {
                                let next_fp = usize::from_le_bytes(buf[0..8].try_into().unwrap());
                                let ret_addr = usize::from_le_bytes(buf[8..16].try_into().unwrap());
                                error!("  frame[{}]: fp={:#x} ret={:#x}", depth, next_fp, ret_addr);
                                fp = next_fp;
                            } else {
                                break;
                            }
                        }
                    }
                    Err(ExceptionType::FatalPageFault)
                }
            }
        }
        TrapReason::UndefinedInstruction => Err(ExceptionType::UndefinedInstruction),
        TrapReason::SoftwareBreakpoint => Err(ExceptionType::SoftwareBreakpoint),
        TrapReason::HardwareBreakpoint => Err(ExceptionType::HardwareBreakpoint),
        TrapReason::UnalignedAccess => Err(ExceptionType::UnalignedAccess),
        TrapReason::GeneralFault(_) => Err(ExceptionType::General),
        _ => unreachable!(),
    }
}

fn syscall_num(ctx: &UserContext) -> usize {
    let regs = ctx.general();
    cfg_if! {
        if #[cfg(target_arch = "x86_64")] {
            regs.rax
        } else if #[cfg(target_arch = "aarch64")] {
            regs.x16
        } else if #[cfg(target_arch = "riscv64")] {
            regs.a7
        } else {
            unimplemented!()
        }
    }
}

fn syscall_args(ctx: &UserContext) -> [usize; 8] {
    let regs = ctx.general();
    cfg_if! {
        if #[cfg(target_arch = "x86_64")] {
            // x86_64 Zircon syscall ABI: first 6 args in registers
            // (rdi, rsi, rdx, r10, r8, r9), 7th and 8th in r12, r13.
            //
            // The Fuchsia vDSO wrapper loads args 7-8 from the C stack
            // into r12/r13 before the `syscall` instruction, because
            // `syscall` only supports 6 register arguments.
            [regs.rdi, regs.rsi, regs.rdx, regs.r10, regs.r8, regs.r9, regs.r12, regs.r13]
        } else if #[cfg(target_arch = "aarch64")] {
            [regs.x0, regs.x1, regs.x2, regs.x3, regs.x4, regs.x5, regs.x6, regs.x7]
        } else if #[cfg(target_arch = "riscv64")] {
            [regs.a0, regs.a1, regs.a2, regs.a3, regs.a4, regs.a5, regs.a6, regs.a7]
        } else {
            unimplemented!()
        }
    }
}

/// Run a petal program directly from an SFS rootfs filesystem.
///
/// This is the rootfs-based boot path for Zircon flavour, analogous
/// to how Linux loads busybox from its rootfs. The petal program is a flat
/// binary (not ELF) loaded at a fixed address.
///
/// This path does NOT use userstart or ZBI -- the kernel loads the program
/// directly, creating a process with the same handle protocol that userstart
/// would provide.
/// Create a `SpawnConfig` for Zircon processes.
///
/// Uses the vDSO and thread_fn from this loader module.
pub fn zircon_spawn_config() -> zircon_object::task::spawn::SpawnConfig {
    let vdso_vmo = create_vdso_vmo();
    let vdso_size = vdso_vmo.len();
    zircon_object::task::spawn::SpawnConfig {
        vdso_vmo,
        vdso_code_size: vdso_size,
        stack_pages: 8,
        thread_fn,
        extra_args: alloc::vec::Vec::new(),
    }
}

/// Boot a Zircon process from a rootfs filesystem.
///
/// `extra_args` are appended to argv after the program name.
pub fn run_from_rootfs(
    rootfs: Arc<dyn rcore_fs::vfs::FileSystem>,
    init_path: &str,
    extra_args: alloc::vec::Vec<alloc::string::String>,
) -> Arc<Process> {
    info!("Zircon rootfs boot: loading '{}'", init_path);

    let inode = rootfs
        .root_inode()
        .lookup(init_path)
        .unwrap_or_else(|e| panic!("failed to find '{}' in rootfs: {:?}", init_path, e));
    let size = inode.metadata().unwrap().size;
    let mut program_data = alloc::vec![0u8; size];
    inode
        .read_at(0, &mut program_data)
        .unwrap_or_else(|e| panic!("failed to read '{}': {:?}", init_path, e));

    info!(
        "Loaded '{}' ({} bytes) from rootfs",
        init_path,
        program_data.len()
    );

    let job = Job::root();
    let mut config = zircon_spawn_config();
    config.extra_args = extra_args;
    zircon_object::task::spawn::spawn_process(&job, "init", &program_data, &config)
        .expect("failed to spawn init process")
}

/// Create a vDSO VMO from the ELF binary and populate data pages.
///
/// For the prebuilt Fuchsia vDSO (x86_64), the ELF has two data pages:
///   `DATA_TIME_VALUES` at offset `0x7000`
///   `DATA_CONSTANTS` at offset `0x8000`
/// These are pre-filled with `0xdeadbeef` and overwritten here.
///
/// For the generated vDSO (aarch64/riscv64), the data page is appended
/// after the ELF content.
fn create_vdso_vmo() -> Arc<VmObject> {
    // Determine the virtual memory size from ELF LOAD segments.
    let vdso_memsize = if VDSO_ELF.len() >= 64 && &VDSO_ELF[0..4] == b"\x7fELF" {
        let e_phoff = u64::from_le_bytes(VDSO_ELF[32..40].try_into().unwrap()) as usize;
        let e_phentsize = u16::from_le_bytes(VDSO_ELF[54..56].try_into().unwrap()) as usize;
        let e_phnum = u16::from_le_bytes(VDSO_ELF[56..58].try_into().unwrap()) as usize;
        let mut max_addr = 0usize;
        for i in 0..e_phnum {
            let ph = &VDSO_ELF[e_phoff + i * e_phentsize..];
            let p_type = u32::from_le_bytes(ph[0..4].try_into().unwrap());
            if p_type == 1 {
                // PT_LOAD
                let p_vaddr = u64::from_le_bytes(ph[16..24].try_into().unwrap()) as usize;
                let p_memsz = u64::from_le_bytes(ph[40..48].try_into().unwrap()) as usize;
                let end = p_vaddr + p_memsz;
                if end > max_addr {
                    max_addr = end;
                }
            }
        }
        max_addr
    } else {
        VDSO_ELF.len()
    };

    let total_pages = vdso_memsize.div_ceil(PAGE_SIZE);
    let vdso_vmo = VmObject::new_paged(total_pages);
    vdso_vmo.set_name("vdso/full");

    if !VDSO_ELF.is_empty() {
        // Write only the loadable portion (up to vdso_memsize or file size,
        // whichever is smaller) to avoid writing debug sections.
        let write_len = VDSO_ELF.len().min(total_pages * PAGE_SIZE);
        vdso_vmo.write(0, &VDSO_ELF[..write_len]).unwrap();
        info!(
            "vDSO: loaded {} bytes of ELF ({} pages, memsize={:#x})",
            VDSO_ELF.len(),
            total_pages,
            vdso_memsize,
        );
    }

    // Populate vDSO data pages.
    if vdso_memsize > 0x8000 {
        // Fuchsia vDSO: DATA_TIME_VALUES at 0x7000, DATA_CONSTANTS at 0x8000.
        // Both are pre-filled with 0xdeadbeef and must be overwritten.

        // DATA_TIME_VALUES (fasttime::internal::TimeValues):
        //   u64 version, i64 ticks_per_second, i64 boot_ticks_offset,
        //   atomic<i64> mono_ticks_offset, u32 numerator, u32 denominator,
        //   u8 usermode_can_access_ticks, u8 a73_errata, u8 use_pct, u8[5] pad
        let mut tv = [0u8; PAGE_SIZE];
        let freq = hal_impl::cpu::cpu_frequency() as u64;
        let tps = freq * 1_000_000;
        // version = 0 (fast-path check uses kFasttimeVersion; 0 ≠ match → returns INFINITE_PAST
        // for kNormal mode, but clock_get_monotonic uses kSkip which bypasses version check)
        tv[8..16].copy_from_slice(&(tps as i64).to_ne_bytes()); // ticks_per_second
                                                                // boot_ticks_offset = 0, mono_ticks_offset = 0 (already zero)
        tv[32..36].copy_from_slice(&1000u32.to_ne_bytes()); // ticks_to_time_numerator
        tv[36..40].copy_from_slice(&(freq as u32).to_ne_bytes()); // ticks_to_time_denominator
        tv[40] = 1; // usermode_can_access_ticks = true
        vdso_vmo.write(0x7000, &tv).unwrap();

        // DATA_CONSTANTS (vdso_constants)
        let vdso_constants = hal_impl::vdso::vdso_constants();
        let constants_bytes = unsafe {
            core::slice::from_raw_parts(
                &vdso_constants as *const _ as *const u8,
                core::mem::size_of_val(&vdso_constants),
            )
        };
        vdso_vmo.write(0x8000, constants_bytes).unwrap();
    } else {
        // Generated vDSO: data page appended after ELF content.
        let data_offset = VDSO_ELF.len().div_ceil(PAGE_SIZE) * PAGE_SIZE;
        let vdso_constants = hal_impl::vdso::vdso_constants();
        let constants_bytes = unsafe {
            core::slice::from_raw_parts(
                &vdso_constants as *const _ as *const u8,
                core::mem::size_of_val(&vdso_constants),
            )
        };
        vdso_vmo.write(data_offset, constants_bytes).unwrap();
    }

    vdso_vmo
}
