[package]
name = "linux-object"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2021"
description = "Linux kernel objects"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mock-disk = []
libos = ["hal-impl/libos"]

[package.metadata.cargo-all-features]
# hal-impl needs libos to compile on the host.
always_include_features = ["libos"]
# mock-disk uses unstable core::intrinsics that are broken on current nightly.
# TODO: fix mock-disk and remove from denylist.
denylist = ["mock-disk"]

[dependencies]
hal = { path = "../hal" }
async-trait = "0.1"
log = "0.4"
xmas-elf = "0.7"
bitflags = "1.3"
hashbrown = "0.9"
numeric-enum-macro = "0.2"
zircon-object = { path = "../zircon-object", features = ["elf"] }
hal-impl = { path = "../hal-impl", default-features = false }
downcast-rs = { version = "1.2", default-features = false }
spin = "0.9"
rcore-fs = { path = "../vfs/rcore-fs" }
rcore-fs-sfs = { path = "../vfs/rcore-fs-sfs" }
rcore-fs-ramfs = { path = "../vfs/rcore-fs-ramfs" }
rcore-fs-mountfs = { path = "../vfs/rcore-fs-mountfs" }
rcore-fs-devfs = { path = "../vfs/rcore-fs-devfs" }
cfg-if = "1.0"
lock = { path = "../lock" }
