use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=src/zx-syscall-numbers.h");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut fout = std::fs::File::create(std::path::Path::new(&out_dir).join("consts.rs")).unwrap();
    writeln!(fout, "// Generated by build.rs. DO NOT EDIT.").unwrap();
    writeln!(fout, "use numeric_enum_macro::numeric_enum;\n").unwrap();
    writeln!(fout, "numeric_enum! {{").unwrap();
    writeln!(fout, "#[repr(u32)]").unwrap();
    writeln!(fout, "#[derive(Debug, Eq, PartialEq)]").unwrap();
    writeln!(fout, "#[allow(non_camel_case_types)]").unwrap();
    writeln!(fout, "#[allow(clippy::upper_case_acronyms)]").unwrap();
    writeln!(fout, "pub enum SyscallType {{").unwrap();

    let data = std::fs::read_to_string("src/zx-syscall-numbers.h").unwrap();
    for line in data.lines() {
        if !line.starts_with("#define ZX_SYS_") {
            continue;
        }
        let mut iter = line.split(' ');
        let _ = iter.next().unwrap(); // #define
        let name = iter.next().unwrap(); // ZX_SYS_xxx
        let id = match iter.next() {
            Some(id) => id,
            None => continue,
        };

        let name = &name[7..].to_uppercase();
        writeln!(fout, "    {} = {},", name, id).unwrap();
    }
    writeln!(fout, "}}").unwrap();
    writeln!(fout, "}}").unwrap();
}
