use std::io::Write;

fn main() {
    if std::env::var("TARGET").unwrap().contains("riscv64") {
        let board = std::env::var("PLATFORM");
        let kernel_base_addr: u64 = if board.map_or(false, |x| x.contains("c910light")) {
            0xffffffe000200000
        } else {
            0xffffffc080200000
        };

        let mut fout = std::fs::File::create("src/platform/riscv/kernel-vars.ld").unwrap();
        writeln!(fout, "/* Generated by build.rs. DO NOT EDIT. */").unwrap();
        writeln!(
            fout,
            "PROVIDE_HIDDEN(BASE_ADDRESS = {:#x});",
            kernel_base_addr
        )
        .unwrap();
    }

    // If linking a rootfs image, set the image path in an environment variable
    #[cfg(feature = "link-user-img")]
    println!(
        "cargo:rustc-env=USER_IMG=zCore/{}.img",
        std::env::var("TARGET").unwrap()
    );
}
