use std::io::Write;

fn main() {
    if std::env::var("TARGET").unwrap().contains("riscv64") {
        let board = std::env::var("PLATFORM");
        let kernel_base_addr: u64 = if board.is_ok_and(|x| x.contains("c910light")) {
            0xffffffe000200000
        } else {
            0xffffffc080200000
        };

        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let ld_path = std::path::Path::new(&manifest_dir).join("src/platform/riscv/kernel-vars.ld");
        let mut fout = std::fs::File::create(&ld_path).unwrap();
        writeln!(fout, "/* Generated by build.rs. DO NOT EDIT. */").unwrap();
        writeln!(
            fout,
            "PROVIDE_HIDDEN(BASE_ADDRESS = {:#x});",
            kernel_base_addr
        )
        .unwrap();
    }

    // If linking a rootfs image, set the image path in an environment variable
    #[cfg(feature = "link-user-img")]
    println!(
        "cargo:rustc-env=USER_IMG=zCore/{}.img",
        std::env::var("TARGET").unwrap()
    );

    // Pass ZCORE_CMDLINE to the kernel as a compile-time env var.
    // Defaults to LOG=warn if not set by the build system.
    println!("cargo:rerun-if-env-changed=ZCORE_CMDLINE");
    let cmdline = std::env::var("ZCORE_CMDLINE").unwrap_or_else(|_| "LOG=warn".to_string());
    println!("cargo:rustc-env=ZCORE_CMDLINE={cmdline}");

    // Force rebuild when any source file in dependency crates changes.
    // Cargo normally tracks source changes, but the rerun-if-env-changed
    // directives above (ZCORE_CMDLINE, PETAL_ZBI, USERSTART_ELF) override
    // the default "rerun if anything changes" behavior. Adding directory
    // watches restores rebuild triggering for dependency source changes.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    for dir in [
        "zCore/linux-object/src",
        "zCore/linux-syscall/src",
        "zCore/linux-loader/src",
        "zCore/zircon-object/src",
        "zCore/zircon-syscall/src",
        "zCore/zircon-loader/src",
        "kernel-hal/src",
    ] {
        let path = workspace_root.join(dir);
        if path.exists() {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    // For Zircon mode: if PETAL_ZBI is not set, generate an empty stub
    // so include_bytes! doesn't fail. The rootfs-based boot path doesn't
    // need the embedded ZBI.
    println!("cargo:rerun-if-env-changed=PETAL_ZBI");
    if std::env::var("PETAL_ZBI").is_err() {
        let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
        let stub = out.join("empty.zbi");
        std::fs::write(stub.as_path(), b"").unwrap();
        println!("cargo:rustc-env=PETAL_ZBI={}", stub.display());
        // Only warn in Zircon mode where the ZBI is actually needed.
        if std::env::var("CARGO_FEATURE_ZIRCON").is_ok() {
            println!("cargo:warning=PETAL_ZBI not set, using empty stub (rootfs-based boot only)");
        }
    }

    // For Zircon mode: if USERSTART_ELF is not set, generate an empty stub.
    if std::env::var("USERSTART_ELF").is_err() {
        let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
        let stub = out.join("empty.elf");
        std::fs::write(stub.as_path(), b"").unwrap();
        println!("cargo:rustc-env=USERSTART_ELF={}", stub.display());
    }
}
