[alias]
xtask = "run --package xtask --release --"
git-proxy = "xtask git-proxy"
update-all = "xtask update-all"

check-style = "xtask check-style"

rootfs = "xtask rootfs"
musl-libs = "xtask musl-libs"
opencv = "xtask opencv"
ffmpeg = "xtask ffmpeg"
libc-test = "xtask libc-test"
other-test = "xtask other-test"
image = "xtask image"

linux-libos = "xtask linux-libos"
petal-zbi = "xtask petal-zbi"

asm = "xtask asm"
bin = "xtask bin"
qemu = "xtask qemu"
gdb = "xtask gdb"
