name: Build CI

on:
  push:
  pull_request:

jobs:
  workspace:
    name: Workspace ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy

  bare-metal:
    name: Bare-metal ${{ matrix.arch }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, riscv64]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, llvm-tools-preview, clippy

      - name: Install cross-compilation toolchain (macOS)
        if: runner.os == 'macOS'
        run: make config

      - name: Install cross-compilation toolchain (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y qemu-utils wget

      - name: Build ${{ matrix.arch }} bare-metal linux
        run: cargo bin -m virt-${{ matrix.arch }}
