# QEMU riscv64 virt machine -- Linux
#
# Standard QEMU virtual machine with 16550 UART (via device tree),
# RISC-V PLIC interrupt controller.

default-flavour = "linux"
arch = "riscv64"
cores = 1
linker-script = "zCore/hal-impl/src/bare/arch/riscv/platform/linker.ld"
drivers = ["uart-16550", "riscv-intc", "riscv-plic", "pci"]

[qemu]
machine = "virt"
memory = "2G"

[rustc-target]
llvm-target = "riscv64"
data-layout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
features = "+m,+a,+c"
os = "none"
llvm-abiname = "lp64"
code-model = "medium"
cpu = "generic-rv64"
max-atomic-width = 64
target-pointer-width = 64
target-endian = "little"
target-c-int-width = 32
relocation-model = "static"
eh-frame-header = false
emit-debug-gdb-scripts = false
